### PR TITLE
Add enable_mesos_input_plugin config option

### PR DESCRIPTION
**Pull request by gracedo**
https://jira.mesosphere.com/browse/DCOS-47301
Adds the `enable_mesos_input_plugin` config option. DCOS PR here: https://github.com/dcos/dcos/pull/4222

I will add the relevant lines to the other cloud provider repos as well.

### CODE REVIEW

**Review by geekbass — CHANGES_REQUESTED** [review]
The code LGTM. Will also need to add this variable to outer modules as well so it can be called from wrapper. Two things here:

1) Should we consider using the variable name `dcos_enable_mesos_input_plugin` since all other variables that concern the DC/OS Config begin with `dcos_`? My answer would be yes. 

2) One other thing, should we consider a hint in the variable description such as adding text like "True or False"

Link to new config variable https://github.com/dcos/dcos/pull/4222.

Adding @fatz for another review.

**Comment by gracedo** [comment]
Thanks @geekbass for reviewing! I will make these changes :)

**Comment by gracedo** [comment]
I've made the var name and description changes here and in all the other repos as well. Let me know if I missed anything! What are the repos for the outer modules that also need these changes?

**Comment by gracedo** [comment]
retest this please

**Review by fatz — APPROVED** [review]
lgtm. Changed the description mapping entry CI job now successful

**Review by geekbass — APPROVED** [review]
LGTM

**Comment by gracedo** [comment]
@fatz @geekbass thanks! Do we need to merge all the other PRs linked to/referenced above as well? (repos for cloud providers etc)

**Comment by geekbass** [comment]
> @fatz @geekbass thanks! Do we need to merge all the other PRs linked to/referenced above as well? (repos for cloud providers etc)

Yes will try to review those today as well.

**Pull request merged**
